spring.application.name=smart-campus-operations-hub

spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

app.jwt.secret=9a4f4c354565456c45624565416245614565434653646564616645624565416245614565
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=javidmushtan@gmail.com
spring.mail.password=kgsx ealc brni lcdr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

spring.datasource.url=jdbc:postgresql://db.bebxgrqhfolrarusmdna.supabase.co:5432/postgres?user=postgres&password=PostgreSQL@2025
spring.datasource.username=postgres
spring.datasource.password=PostgreSQL@2025
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.hateoas.use-hal-as-default-json-media-type=true
