spring.application.name=smart-campus-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_campus
spring.datasource.username=postgres
spring.datasource.password=Safiya@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OAuth2 Configuration (Google)
# NOTE: Replace with your actual Client ID and Secret
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# JWT Configuration
app.jwt.secret=9a4f4c354565456c45624565416245614565434653646564616645624565416245614565
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# Server Configuration
server.port=8081

# HATEOAS Configuration
spring.hateoas.use-hal-as-default-json-media-type=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=javidmushtan@gmail.com
spring.mail.password=kgsx ealc brni lcdr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true